"""config 子包 — 统一配置管理"""

import os
from dotenv import load_dotenv

load_dotenv()

from src.config.constants import (
    API_BASE_URL, API_KEY, MODEL_NAME, EMBEDDING_MODEL,
    SENDER_EMAIL, AUTH_CODE, RECEIVER_EMAIL, SMTP_SERVER, SMTP_PORT,
    BASE_DIR, HTML_FILE, HTML_TEMPLATE, EMAIL_TEMPLATE, EMAIL_OUTPUT, CRAWL_LOG_FILE,
    SITE_URL,
    SOURCE_HEALTH_FILE, SOURCE_HEALTH_MAX_FAILURES,
    SUMMARY_MAX_LENGTH,
    DEDUP_MINHASH_THRESHOLD, DEDUP_SEMANTIC_THRESHOLD, DEDUP_EMBEDDING_BATCH,
    URL_DB_FILE, EMBEDDING_CACHE_FILE,
    CREDIBILITY_SCORE_THRESHOLD,
    now_bjt,
)
from src.config.sources import (
    RSS_SOURCES, MAX_PER_SOURCE, RSS_FALLBACKS,
    CHINESE_SOURCE_NAMES, CHINESE_CRAWLER_SOURCE_MAP,
    CREDIBILITY_WHITELIST, CREDIBILITY_BLACKLIST,
)
from src.config.prompts import (
    SYSTEM_PROMPT_MINIMAL, SYSTEM_PROMPT_SARCASTIC, SYSTEM_PROMPT_DEEP,
    SYSTEM_PROMPT_GEEK, SYSTEM_PROMPT_WEIBO, SYSTEM_PROMPT_PM,
    SYSTEM_PROMPTS,
    get_random_style, get_random_trivia,
)
from src.config.trending_tags import (
    PROJECT_CATEGORY_ORDER, TOPIC_TO_CATEGORY, KNOWN_REPOS,
    DESC_KEYWORD_WEIGHTS, classify_repo,
)
from src.config.trivia import AI_TRIVIA
